[project]
name = "lightme"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12,<3.14"
dependencies = [
    "docx2txt>=0.9",
    "edge-tts>=7.2.8",
    "fastapi>=0.135.2",
    "firecrawl>=4.25.2",
    "langchain>=1.2.15",
    "langchain-chroma>=1.1.0",
    "langchain-community>=0.4.1",
    "langchain-litellm>=0.6.4",
    "langchain-openai",
    "langchain-text-splitters>=1.1.1",
    "litellm>=1.83.7",
    "markdown>=3.10.2",
    "ntplib>=0.4.0",
    "openai>=2.29.0",
    "pillow>=12.2.0",
    "pyautogui>=0.9.54",
    "pypdf>=6.9.2",
    "pywebview>=6.1",
    "pyyaml>=6.0.3",
    "tavily-python>=0.7.24",
    "ui-tars>=0.5.1",
    "unstructured>=0.21.5",
]
